### ISSUE TITLE
Docker build runs with all pushes from feature branches

### ISSUE THREAD

**Issue by iyourshaw** [usdot-jpo-ode/jpo-conflictmonitor#30]
While working on a new feature branch I'm noticing it is running the full workflow to build a docker image every time I push a commit on the feature branch.   This seems wasteful of CI resources. It looks like the intention in the workflow file is to ignore pushes and only run on pull requests, see the branches-ignore section here:

```yaml
name: Docker build

on:
  push:
    branches-ignore:
      - "develop"
      - "master"
      - "release/*"
  pull_request:

jobs:
  jpo-conflictmonitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
```

Suggestion: remove the "branches-ignore" section, so that Docker builds are only triggered by pull requests, ignoring pushes for all branches.  See the `docker-workflow-ignore-pushes` branch: 
https://github.com/usdot-jpo-ode/jpo-conflictmonitor/blob/docker-workflow-ignore-pushes/.github/workflows/docker.yml
